### ISSUE TITLE
Python keyword arguments

### ISSUE THREAD

**Issue by knyghty** [atom/one-dark-syntax#18]
Really like that this is the default theme now, but one thing different from Atom Dark that I find annoying is that keyword arguments in Python aren't highlighted. So if I have for example:

    spam(ham, eggs='foo')

This would highlight eggs (but not ham). I'm quite used to this and I feel like I'm missing some instant grokability without it.

**Comment by simurai** [comment]
@knyghty The Atom Dark theme seems to highlight only `eggs` but not `ham`.

![screen shot 2015-04-03 at 11 47 03 am](https://cloud.githubusercontent.com/assets/378023/6977398/3f0e5870-d9f7-11e4-9b7c-69994c8bd537.png)

And the One Dark theme highlights neither.

![screen shot 2015-04-03 at 11 45 14 am](https://cloud.githubusercontent.com/assets/378023/6977403/606f2abc-d9f7-11e4-86b5-ee62343990df.png)

I think it would be possible to highlight `eggs` in One Dark too. But not sure if also `ham`. Because there isn't an element that can be styled.

![screen shot 2015-04-03 at 11 51 17 am](https://cloud.githubusercontent.com/assets/378023/6977441/13f6d364-d9f8-11e4-834a-8ba854e58ee5.png)

Maybe you can create an new issue on the python repo: https://github.com/atom/language-python.

**Comment by knyghty** [comment]
That's correct. Sorry if I didn't make that clear enough. I'm not sure if highlighting the non-keyword arguments is necessary - I don't feel it lacking without it at least..

**Comment by taylon** [comment]
Just created a pull request for this, I also think that non-keyword don't need to be highlighted, but keywords does, I think that is the most expected for Python, and it's not a problem for most syntaxes since they usually set .variable.parameter to something else than the base text color
