### ISSUE TITLE
Operators aren't highlighted

### ISSUE THREAD

**Issue by Victorystick** [atom/one-dark-syntax#44]
Currently operators like `+`,`!==`, `||`, `typeof` and `new` aren't highlighted in JavaScript.

![screen shot 2015-09-07 at 16 22 56](https://cloud.githubusercontent.com/assets/703602/9718512/bef3a526-557c-11e5-9793-c04abdcadf5d.png)

Is this intended behaviour?

**Comment by lee-dohm** [comment]
Operators are highlighted:

https://github.com/atom/one-dark-syntax/blob/master/styles/language.less#L26-L28

But they are colored the same as default text:

https://github.com/atom/one-dark-syntax/blob/master/styles/colors.less#L13-L14

I can't speak as to whether it is intended behavior or not.

**Comment by simurai** [comment]
> Is this intended behaviour?

Yes, that's intended. Well, this theme is based on `base16-tomorrow` where the same question came up: https://github.com/atom/base16-tomorrow-dark-theme/issues/13

I think there it should stay true to the original theme and not have a different color for operators. Just because the name makes people expect it to be the same.

Now if One dark should start "its own life" is another question.

**Comment by djch** [comment]
> Now if One dark should start "its own life" is another question.

'course it should—it's the default theme for a rather popular text editor, unlike Tomorrow Dark :-]

**Comment by simurai** [comment]
So this question came up again in https://github.com/atom/language-javascript/issues/273 and https://github.com/atom/language-javascript/issues/274.

Here the before/after if `operator`s have the same color as other `keyword`s:

```js
function add ( x, y ) {
  if ( typeof x != 'number' || typeof y !== 'number') {
    throw new TypeError('Can only add numbers!');
  }

  return x + y;
}

function destoryCompleted() {
  for (var id in _todos) {

var a = {};
a.foo = 'bar';
delete a.foo;
```

Before:

<img width="486" alt="screen shot 2015-12-06 at 2 20 22 pm" src="https://cloud.githubusercontent.com/assets/378023/11616021/a0e60cec-9c24-11e5-9bc4-5948a6889799.png">

After:

<img width="490" alt="screen shot 2015-12-06 at 2 03 25 pm" src="https://cloud.githubusercontent.com/assets/378023/11616026/b0d1bd04-9c24-11e5-88fb-1ca161f3cfca.png">

Hmm.. I usually prefer not to colorize too much just so that not everything asks for attention.

Anyone strongly thinks it should be the new default? Here you can try it out how it feels in `styles.less` with One dark:

```less
.theme-one-dark-syntax atom-text-editor::shadow {
  .keyword.operator.js {
    color: #c678dd;
  }
}
```
