### ISSUE TITLE
Please lighten the comment

### ISSUE THREAD

**Issue by DrakeXiang** [atom/one-dark-syntax#69]
The comment in one-dark-syntax is a little hard to read, even though I love the rest part, this drawback is painful.

**Comment by mmcbride1007** [comment]
In your own stylesheet.less you can actually override the comment color. The class you want to target is .comment.

Something like this might work for you:

.comment { color: #[lighter color]; }

**Comment by DrakeXiang** [comment]
Thanks @mmcbride1007 , I thought this is an issue not only to myself, so if we can get official fix would be great.

**Comment by mmcbride1007** [comment]
I understand where you are coming from, but I think that's just preference and not an actual issue with the package. For instance, I personally like the comments to be subtle because I don't want them distracting me when I scan the code. Since it's what the package author intended it to look like, your best bet is probably overriding this in your stylesheet. You could always submit a PR as an enhancement request and get some feedback too, though :smile:

**Comment by simurai** [comment]
@DrakeXiang Thanks for your suggestion. Contrast is something that is pretty hard to get right for everyone. Depends on many factors. If we would lighten comments there will be people that want it darker again. We could consider it again once we start working on the next major version of this theme (no plans yet).

For now it needs to be adjusted in your `styles.less`.. something like:

```less
atom-text-editor::shadow {
  .comment {
    color: hsl(200, 10%, 50%); // original hsl(200, 10%, 40%)
  }
}
```

(the last % number is lightness)
