### ISSUE TITLE
Symbols are the same color as strings (Ruby)

### ISSUE THREAD

**Issue by mnquintana** [atom/one-dark-syntax#8]
I've noticed that in Ruby, symbols are now the same color as strings, which makes it kind of hard to figure out just from the color scheme whether something is a symbol or string.

**One Dark:**
![image](https://cloud.githubusercontent.com/assets/823545/5881246/34d5e93e-a30d-11e4-9042-417e88e918e0.png)

**Atom Dark:**
![image](https://cloud.githubusercontent.com/assets/823545/5881234/1c92d4b8-a30d-11e4-985e-08d8a18c3c73.png)

(Also applies to [one-light-syntax](https://github.com/atom/one-light-syntax))

**Comment by simurai** [comment]
[symbols](https://github.com/atom/one-dark-syntax/blob/master/stylesheets/language.less#L60) are indeed the same color as [strings](https://github.com/atom/one-dark-syntax/blob/master/stylesheets/language.less#L82). Symbols could be replaced with any of [these](https://github.com/atom/one-dark-syntax/blob/master/stylesheets/colors.less#L40-L48).

Maybe `@bright-orange`?

![screen shot 2015-01-24 at 6 52 13 pm](https://cloud.githubusercontent.com/assets/378023/5886950/33b01852-a3fa-11e4-9e8a-ce40dd09003b.png)

**Comment by mnquintana** [comment]
`@bright-orange` would definitely be better, and seems to be one of the only colors that wouldn't clash too much, but aesthetically I'm not sure I like it. It's a bit too... I dunno, bright and saturated? Enough that it's a little distracting. 

I looked at all the other available colors, and they all clashed too much except `@cyan`, but that one was a bit too subtle. Personally, I think it might be worth adding another shade of blue to the color scheme, something stronger than `@blue` and `@cyan` – that seems like it would work well for symbols.

**Comment by simurai** [comment]
Actually `@blue` should be a bit stronger in general since it's very close to the normal text. Adding another darker blue, might be too much blue? Not in your context, but in others. This theme is based on "base16 tomorrow" but I think it's ok to tweak the colors a bit. Made a new branch `sm-improve-colors`: https://github.com/atom/one-dark-syntax/tree/sm-improve-colors

Your example would look like this:

![screen shot 2015-01-27 at 9 51 28 pm](https://cloud.githubusercontent.com/assets/378023/5918765/b7239e44-a66f-11e4-8135-755390748200.png)

Another ruby example like this:

![screen shot 2015-01-27 at 10 00 03 pm](https://cloud.githubusercontent.com/assets/378023/5918778/e370ad70-a66f-11e4-8fe2-2ebc06ca2926.png)

**Comment by simurai** [comment]
The colors will probably change some more. Maybe even try another scheme. Base16 Tomorrow just seemed the most fitting.

**Comment by mnquintana** [comment]
@simurai Thanks for taking a look at this! I have one more symbols request (I could open a new issue for this if you want but it seems too minor for that) – could you change the `:` color from orange to `@cyan` to match the symbol color? In Ruby the `:` isn't an operator like in many other languages, it's a part of the syntax for writing symbols, so it's a little weird for it to be a different color.

**Comment by simurai** [comment]
Ohh.. right, you mentioned that above. It's not just the `:` in front of a symbol, also the one after, right? Pushed a fix like this:

![screen shot 2015-01-29 at 9 59 36 pm](https://cloud.githubusercontent.com/assets/378023/5957907/3de3fec2-a802-11e4-8448-e66e197c432a.png)

**Comment by mnquintana** [comment]
Yup! Perfect. Thanks!
