### ISSUE TITLE
1.6.0 breaks syntax highlighting on one light/dark

### ISSUE THREAD

**Issue by chibicode** [atom/one-dark-syntax#80]
After upgrading to 1.6.0, on both one dark and one light, none of the syntax highlighting is working:

![image](https://cloud.githubusercontent.com/assets/992008/19449381/3cd97192-945a-11e6-8c21-88d54abec61f.png)

My Atom version is 1.11.1 and there's nothing on my styles.less.

**Comment by 50Wliu** [comment]
Don't manually update unless you know what you're doing.

**Comment by chibicode** [comment]
@50Wliu ah, I was using [auto-update-packages](https://github.com/yujinakayama/atom-auto-update-packages) and it seems that it updated bundled packages as well.

**Comment by bradpurchase** [comment]
This is a completely ridiculous response to this issue. An update for this syntax theme showed up in my updates list this morning, I updated, and then the syntax highlighting was completely broken (I'm not using auto-update-packages or anything of the sort). And the response from the Atom team is "don't manually update bundled packages unless you know what you're doing"? 😕 

Is a casual user supposed to just "know" not to update One Dark because it comes bundled? I fixed it by removing `one-dark-syntax` inside `~/.atom/packages`, but a casual user would likely not know to do this. Searching for help would lead them here and they'd get turned away because _they_ messed up. Right.

Here's a much more helpful answer: https://github.com/atom/base16-tomorrow-dark-theme/issues/33#issuecomment-254323567

**Comment by 50Wliu** [comment]
> Is a casual user supposed to just "know" not to update One Dark because it comes bundled?

Yes, because bundled packages **never** show up as candidates for updates unless one of two things happen:
1. You manually install it (which gives you a fairly large warning in the terminal when you do)
2. You are using a package which auto-updates packages for you

This is why the response I gave is what I gave.
