### ISSUE TITLE
Syntax highlight broken after update

### ISSUE THREAD

**Issue by ruslankonev** [atom/one-dark-syntax#82]
In other selected themes – all fine

![image](https://cloud.githubusercontent.com/assets/2588730/20516332/24d11da2-b0a7-11e6-9734-51d679a8e05f.png)

**Comment by Ben3eeE** [comment]
This is because you have manually installed `atom-dark-syntax` at some point causing you to get update notifications for this package. This package is only supposed to be updated along with Atom.

You should uninstall the version you have installed using `apm uninstall one-dark-syntax` which will make it so you use the bundled version instead which is designed for Atom 1.12.

**Comment by ruslankonev** [comment]
I update theme not by manually, I update by notification by Atom. After restart Atom only one-dark-theme & syntax was not highlight any language

**Comment by simurai** [comment]
> Unfortunately `apm uninstall one-dark-syntax` & `apm install one-dark-syntax` will not help me.

@Ben3eeE  meant to **only** uninstall one-dark-syntax and not re-install it after again. So could you try to:

1. Run `apm uninstall one-dark-syntax`
2. Reload Atom

Now Atom will use the right version of one-dark-syntax, the one that is already included (bundled) with Atom.

**Comment by ruslankonev** [comment]
> @Ben3eeE meant to only uninstall one-dark-syntax and not re-install it after again. So could you try to:

And this will not help..

**Comment by simurai** [comment]
> And this will not help..

Just to be sure.. if you go to "Settings > Themes", do you see one-dark-syntax `1.6.0` under "Community Themes"?

<img width="900" alt="screen shot 2016-11-22 at 9 19 01 pm" src="https://cloud.githubusercontent.com/assets/378023/20524094/fe84b460-b0fb-11e6-937c-8ffcae285d27.png">

`apm uninstall one-dark-syntax` + reload Atom should remove it so that only one-dark-syntax `1.5.0` under "Core Themes" is installed.

Another option is to try [Atom Beta](https://atom.io/beta). There one-dark-syntax `1.6.0` should already work.

**Comment by ruslankonev** [comment]
I have installed only one-dark-syntax 1.5.0, and this version will not highlight language with colors. After update something was going wrong.
![image](https://cloud.githubusercontent.com/assets/2588730/20524352/4190a81c-b0cb-11e6-9e5c-9526ff8f8e6a.png)

**Comment by ruslankonev** [comment]
Wow, in beta syntax also now working. I think something in local settings or packages was broken

![image](https://cloud.githubusercontent.com/assets/2588730/20524768/1dba00e4-b0cd-11e6-9205-9634504e9725.png)

**Comment by ruslankonev** [comment]
In my case I found what happens with editor. Somehow was shutdown language-javascript package — I see what code shown in "Plain Text" mode. In my case issue was closed, but https://github.com/atom/atom/issues/13294#issuecomment-262234540

**Comment by gusbemacbe** [comment]
But in my Atom, Javascript syntax was still enabled and it wasn't colourful.

**Comment by simurai** [comment]
Ok, let's move back to https://github.com/atom/atom/issues/13294 :grinning:
